# MAIN DATA -------------------------------------------------------------------
# Site data
site_name: Settimana Bianca 2k25
site_url: "http://rufusxx.github.io/settimana-bianca/"
site_author: rufusxx
site_description: >-
  La vacanza sulla neve che non ti immagini!

# Repository
repo_name: rufusxx/settimana-bianca
repo_url: https://github.com/rufusxx/settimana-bianca
edit_uri: ""

# Navigation bar
nav:
- Benvenuto!: generale.md
- Informazioni: info/info.md
- Contatti: contatti.md

# THEME -----------------------------------------------------------------------
# Theme
theme:
  name: "material"
  icon:
    logo: fontawesome/solid/person-skiing
  favicon: assets/favicon.png
  palette:
    scheme: rufusxx
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
  custom_dir: docs/overrides

# Custom colors
extra_css:
  - stylesheets/extra.css
  - stylesheets/hero.css

# PLUGINS AND MARKDOWN EXTENSIONS ---------------------------------------------
# Plugins
plugins:
- gh-admonitions
#- search
- autorefs
- section-index

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg