name: settimana-bianca
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.7
  - pip=23.3.1
  - mkdocs=1.6.1 
  - mkdocs-material=9.5.44
  - mkdocs-autorefs=1.2.0
  - pip:
    - mkdocs-section-index==0.3.9
    - mkdocs-github-admonitions-plugin==0.0.3